---
# tasks file for golem-dev-mac

#install geth
- name: add geth repo
  become_user: "{{ buildbot_user }}"
  homebrew_tap:
    name: "{{ geth_repository }}"

- name: install geth and dependencies
  become_user: "{{ buildbot_user }}"
  homebrew:
    name: "{{ item }}"
  with_items:
    - ethereum
    - automake
    - pkg-config
    - libtool
    - libffi
    - gmp


# install hyperg
- name: install tar
  become_user: "{{ buildbot_user }}"
  homebrew:
    name: gnu-tar
    options:
      - with-default-names

# Link gtar to replace tar
- lineinfile:
    create: yes
    path: ~/.bashrc
    line: "export PATH={{ hyperg_link_target_dir }}:$PATH"

- name: Prepare hyperg directory
  become: yes
  file:
    dest: "{{ hyperg_base_dir }}"
    state: directory

- name: download hyperg
  become: yes
  unarchive:
    remote_src: yes
    src: "{{ hyperg_package_url }}"
    dest: "{{ hyperg_base_dir }}"
  args:
    creates: "{{ hyperg_install_dir }}"


- name: Link hyperg
  file:
    src: "{{ hyperg_install_dir }}/hyperg"
    dest: "{{ hyperg_link_target_dir }}/hyperg"
    state: link


# install pythons
- name: install python and deps
  become_user: "{{ buildbot_user }}"
  homebrew:
    name: "{{ item }}"
  with_items:
    - python3
    - openexr
    - freeimage


- name: install buildbot venv
  pip:
    executable: pip3
    name: virtualenv
